site_name: Hrishi's Archive

theme:
  name: material
  logo: assets/images/caticon.png
  favicon: assets/images/caticon.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  language: en

  font:
    text: Fira Sans
    code: Ubuntu Mono


nav:
  - Home: index.md
  - Robosoccer: 
    - Overview: robosoccer/index.md
    - The Bot: robosoccer/bot.md
  - Quadcopter:
    - Overview: quadcopter/index.md
    - Anatomy: quadcopter/anatomy.md
    - Components:
        - Motors: quadcopter/motors.md
        - Frame: quadcopter/frame.md
  - Maze Solver:
    - Overview: maze-solver/index.md
    - Components: maze-solver/components.md
    - Mazes: maze-solver/mazes.md
    - Algorithms: maze-solver/algorithms.md
  - Data Structures:
    - Overview: ds/index.md
  - Algorithms:
    - Overview: algo/index.md
  - Common:
    - Motors: common/motors.md
  - Blogs:
    - ESC interfacing issue with pixhawk: random/pixhawk-simonk-issue.md
    - Ubuntu wifi not working: random/dual-boot-wifi-issue.md
    - Free Unlimited Cloud Storage: random/free-unlimited-cloud-storage.md
    - Simple python venv manager: random/simple-python-venv-manager.md 
    - Install and Setup OpenGL Developer Environment: random/install-and-setup-opengl-dev-environment.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
